name: Build and Test
run-name: ${{ github.actor }} is building project
on: [push, pull_request]
env: 
  CARGO_TERM_COLOR: always
jobs:
  build_and_test:
    name: Graph - Rust - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
         - stable
         - beta
         - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose 
